# Generated by Django 4.2.7 on 2025-07-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
